# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

accumulate_evidence_ddm_naive <- function(A, V, ndt, dt, max_reached, max_t, noise_mechanism = "add") {
    .Call('_multieam_accumulate_evidence_ddm_naive', PACKAGE = 'multieam', A, V, ndt, dt, max_reached, max_t, noise_mechanism)
}

